### ISSUE TITLE
Unifying Libraries?

### ISSUE THREAD

**Issue by malkomalko** [aksonov/react-native-redux-router#5]
Hi @aksonov,

First off, thank you for your flux router as it gave us inspiration for our redux routing implementation that we started working on before you released this library.  We have made a few enhancements, and I was wondering if you wanted to merge efforts into our library with any ideas you may have.  Please let us know.

https://github.com/Qwikly/react-native-router-redux

Chers,
Rob

**Comment by aksonov** [comment]
Since most code of original react-native-router-flux, your 'inspired' react-native-router-redux and this redux-router is the same, the best idea was to unite them into original react-native-router-flux 2.0 version with possibility to choose flux implementation (alt, redux or whatever user wants).

I was big surprise for me when i was not be able to register react-native-router-redux because it was registered just few hours earlier, but nobody notified me in advance about such plans as well as about 'inspired' stuff (it could be done within several 'redux' issues). It would save me time so i would not start working on redux version and use your implementation instead.

I know, this is open source world, but it doesn't look good - instead of doing PRs to improve original component together, clone component, add few improvements and represent it as 'your' library...

**Comment by malkomalko** [comment]
Sorry @aksonov it was definitely an oversight not to reach out to you sooner when we were thinking about working on this library.  It really is coincidence that we started at the same time and I'm sorry for that.

We're more than happy to change the name if you want, just let us know.  If you want to be the source and we can create a fork off that, that's fine too.  Either way, I was just trying to extend a hand here.

**Comment by aksonov** [comment]
I really don't understand why you just didn't send PR for Redux support inside react-native-router-flux component - it would be real extending a hand. I would really enjoy to add you as collaborator and work on 2.0 version together.

**Comment by aksonov** [comment]
Closing this "issue". Hope you will not stole my code anymore without including my (c) according to MIT license.
